=== ffpy/EasySpider/xsd/easycrawler_mapper.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mappers">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="request">
                    <xs:complexType>
                        <xs:attributeGroup ref="request_attrs"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mapper">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="property">
                                <xs:complexType>
                                    <xs:attributeGroup ref="property_attrs"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sub">
                                <xs:complexType>
                                    <xs:attributeGroup ref="sub_attrs"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attributeGroup ref="mapper_attrs"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attributeGroup ref="mappers_attrs"/>
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="mappers_attrs">
        <xs:attribute name="namespace" use="required"/>
        <xs:attribute name="itemSelector"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="request_attrs">
        <xs:attribute name="id"/>
        <xs:attribute name="url"/>
        <xs:attribute name="charset"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="mapper_attrs">
        <xs:attribute name="id" use="required"/>
        <xs:attribute name="request"/>
        <xs:attribute name="itemSelector"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="property_attrs">
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="selector" use="required"/>
        <xs:attribute name="content" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="text"/>
                    <xs:enumeration value="html"/>
                    <xs:enumeration value="src"/>
                    <xs:enumeration value="abs_src"/>
                    <xs:enumeration value="href"/>
                    <xs:enumeration value="abs_href"/>
                    <xs:enumeration value="value"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="pattern"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="sub_attrs">
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="selector"/>
        <xs:attribute name="mapper"/>
    </xs:attributeGroup>
</xs:schema>

=== ffpy/EasySpider/easyspider-sample/target/test-classes/easyspider-qidian.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mappers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../xsd/easycrawler_mapper.xsd"
         namespace="org.ffpy.easyspider.sample.qidian.Qidain">
    <request id="bookInfo" url="https://book.qidian.com/info/{id}" charset="utf8"/>

    <mapper id="getBookInfo" request="bookInfo">
        <property name="name" selector=".book-info h1 em" content="text"/>
        <property name="author" selector=".book-info .writer" content="text"/>
        <property name="intro" selector=".book-info-detail .book-intro p" content="html"/>
        <sub name="catalogs" mapper="getBookCatalog"/>
        <sub name="score" mapper="getBookScore"/>
        <sub name="fans" mapper="getFans"/>
        <property name="testDate" selector="#testDate" content="text" format="yyyy-mm-dd"/>
    </mapper>

    <mapper id="getBookCatalog" request="bookInfo"
            itemSelector=".catalog-content-wrap .volume-wrap .cf li">
        <property name="name" selector="a" content="text"/>
        <property name="url" selector="a" content="abs_href"/>
    </mapper>

    <mapper id="getBookScore" request="bookInfo">
        <property name="value" selector="#j_bookScore" content="text"/>
        <property name="count" selector="#j_userCount" content="text" pattern="(\d*)"/>
    </mapper>

    <mapper id="getFans" request="bookInfo">
        <sub name="recommend" mapper="getRecommend"/>
        <sub name="reward" mapper="getReward"/>
    </mapper>

    <mapper id="getRecommend" request="bookInfo">
        <property name="week" selector="#recCount" content="text"/>
        <property name="rank" selector="#ticket-wrap .ticket" content="text" pattern="排名(\d*)"/>
    </mapper>

    <mapper id="getReward" request="bookInfo">
        <property name="week" selector=".rewardNum" content="text"/>
        <property name="today" selector="#todayNum" content="text"/>
    </mapper>
</mappers>
